function [dTheta] = computeThetaDerivative(h, mod)
    dTheta = (h<0) .* mod.alpha .* ...
             mod.n .* (-mod.alpha .* h) .^ (mod.n - 1) .* mod.m .* ...
             ((-mod.alpha .* h) .^ mod.n + 1) .^ (-mod.m - 1);
end