function [dKr] = computeKrDerivative (h, mod)
    ah = - mod.alpha .* h;
    dKr = (2 .* (ah .^ mod.n + 1).^(- mod.m / 2) .* ...
          (1 - ah .^ (mod.n - 1) .* (ah .^ mod.n + 1) .^ (- mod.m)) .* ...
          (mod.alpha .* mod.m .* mod.n .* ah .^ (2 .* mod.n - 2) .* ...
          (ah .^ mod.n + 1) .^ (- mod.m - 1) - mod.alpha .* ...
          (mod.n - 1) .* ah .^ (mod.n - 2) .* (ah .^ mod.n + 1) .^ ...
          (- mod.m)) - 0.5 .* mod.alpha .* mod.m .* mod.n .* ah .^ ...
          (mod.n - 1) .* (ah .^ mod.n + 1) .^ (- mod.m / 2 - 1) .* ...
          (1 - ah .^ (mod.n - 1) .* (ah .^ mod.n + 1) .^ (- mod.m)) .^ 2);
    dKr(h >= 0) = 0;
end