function [theta] = computeTheta(phi, mod)                         % eq. (6)
    theta = (phi >= 0) .* mod.thetaS + (phi < 0) .* ...
            (mod.thetaR + (mod.thetaS - mod.thetaR) .* ...
            (1 + (-mod.alphaMvG .* phi) .^ mod.n) .^ (-mod.m));
end
